dist: trusty
sudo: required
language: node_js
node_js:
- '8'
before_cache:
- nix-collect-garbage -d
cache:
  directories:
  - node_modules
  - nix
  timeout: 9000
before_install:
- sudo mkdir -m 0755 /nix && sudo chown travis /nix
- sudo mount -o bind /home/travis/build/makerdao/makerdao-integration-poc/nix /nix
- curl https://nixos.org/nix/install | sh
- ". /home/travis/.nix-profile/etc/profile.d/nix.sh"
- nix-channel --add https://nix.dapphub.com/pkgs/dapphub
- nix-channel --update
- nix-env -iA dapphub.{dapp,seth,hevm,solc}
- npm i -g npm@latest
install:
- npm install
- npm run build:backend
- npm run build:frontend
before_script:
- npm install -g codecov
script:
- chmod +x with-deployed-system update-abis
- npm run test
- codecov
after_install:
- cat /home/travis/.npm/_logs/2018-02-*.log
before_deploy: "npm version && npm run build:backend && cd dist"
deploy:
  provider: npm
  email: ebennett19@gmail.com
  api_key:
    secure: "05LnYn4SIg9N6zngVM1QFRz0Yw+66TmKTC2HPZVhxshk3Of1Ry+Kk4wlUnH/o/o3KrZvJiJvriJHXrioJyD21OOjuPfTVg+o69Gwq9CMtbWWsWZN9OXe+Z/N4Vdw3nnA9pdqmaKt9XlrPE+BEK97zXTWsSkc4SO8NHGjME0TV38t3gJjCPLRGRceT54kS6FkU0E+tnEaVYZuqHchoGiV5lIAzYjNBLjbaPi3+r9L3r5BP8eWMAbYJmmpt9H3/ZNt1XsZtvwFcuEcXyC/9W/Oe0d0n90HIyss40jJDrWur+fIS3yEZ9ersxLvDL8/Q9zOL1O9ltbO6o/mfgTFIA7FUIbOVkYw3QnvV9fVpOIShm4kHIQ/3Xbt5X8XyawxRAAkpbjSnKx651NJ89ckzEZr1LJZsDhycb6ZG4Q/ZgU7Ff5dC00iFpyVGkTGqsP7+CsBJSFlcB4m/YLGeX2ZoEruMHWMbbZ4NVx1rFH/lR0Z67lD1OhgDCPRjcHkxMSBUHkMIkAKLhKNb9uRXeA/huO9efKXvZf1V+Ch20VUneOdAny7Lmk6GVfdkvnskf4NeO2D230hqVV53E5aey8KlVn5sCqCP8nr3w1TU9vao5i0d+6SALmU2BTH+FJJ6GOtpnSiIORoSgbGzEk9XHIYmoVxt4c+ZGTt4CxAt6Ah/YVnGEg="
  skip_cleanup: true
  on:
    branch: dev
    tags: true
  